language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="irc-client:. irc-client-unix:. irc-client-lwt:."
  - DISTRO="ubuntu-20.04"
  matrix:
  - PACKAGE="irc-client" OCAML_VERSION="4.03"
  - PACKAGE="irc-client" OCAML_VERSION="4.04"
  - PACKAGE="irc-client" OCAML_VERSION="4.06"
  - PACKAGE="irc-client" OCAML_VERSION="4.07"
  - PACKAGE="irc-client" OCAML_VERSION="4.08"
  - PACKAGE="irc-client" OCAML_VERSION="4.09"
  - PACKAGE="irc-client" OCAML_VERSION="4.10"
  - PACKAGE="irc-client" OCAML_VERSION="4.11"
  # also test that the other libraries build
  - PACKAGE="irc-client-lwt" OCAML_VERSION="4.06"
  - PACKAGE="irc-client-lwt-ssl" OCAML_VERSION="4.06"
  - PACKAGE="irc-client-tls" OCAML_VERSION="4.07"
  - PACKAGE="irc-client-unix" OCAML_VERSION="4.07"
  - PACKAGE="irc-client-lwt" OCAML_VERSION="4.11"
  - PACKAGE="irc-client-lwt-ssl" OCAML_VERSION="4.11"
  - PACKAGE="irc-client-tls" OCAML_VERSION="4.11"
  - PACKAGE="irc-client-unix" OCAML_VERSION="4.11"
